### ISSUE TITLE
Viper architecture

### ISSUE THREAD

**Issue by potty0** [NativeDevelopmentMeetup/NativeDevelopmentMeetup#1]
This talk is a high level overview about a software architecture called VIPER. With some clever abstractions and simple rules a healthy and maintainable codebase can be developed. We all know that there is no such thing as a silver bullet so I would like to highlight a couple of downfalls also. Some thoughts about testing will also be covered. (The experience I would like to share is based on two existing project in production.)

**Comment by vasarhelyia** [comment]
:+1:
