### ISSUE TITLE
Evolution of asynchronous processing and parallelization in .NET

### ISSUE THREAD

**Issue by bardospeter** [NativeDevelopmentMeetup/NativeDevelopmentMeetup#10]
Although .NET is just 13 years old, in the last couple years there were a lot of changes in how we deal with parallelism and asynchronicity. New techniques are making it easy, to deal with these tricky situations, but some of us still has to work with legacy code, and has no chance to deep dive into these cool technologies. Therefore, I'll give a brief overview about the existing framework solutions.

**Agenda:**

Scheduling
Overview of threading patterns
Overview of asynchronous patterns 

**Peter Bardos**
Software Engineer
**Prezi**

**Comment by vasarhelyia** [comment]
:+1:
