### ISSUE TITLE
How can kotlin change android development

### ISSUE THREAD

**Issue by mateherber** [NativeDevelopmentMeetup/NativeDevelopmentMeetup#11]
While android development using java is perfectly fine and you can achieve everything you want, it's expressiveness leaves a lot to be desired. While java 8 has a lot of cool features, android developers stuck somewhere between 6 and 7. Having no word about the future of android development from Google, kotlin seems to solve a lot of issues an android developer faces every day and also brings clean code to the table. Doing all these in a 100% java interoperable way. Even though we don't use kotlin yet at Skyscanner, I'd like to make everybody excited about kotlin by showcasing some of its features through an android dev's eye.

**Agenda:**
- Introducing kotlin
- Why kotlin can be relevant for android
- What makes kotlin better (syntax vs java)
- What makes kotlin the best (language features)
- Kotlin goodies for Android

**Mate Herber**
Software Engineer
**Skyscanner**

**Comment by vasarhelyia** [comment]
:+1:
