### ISSUE TITLE
How I become the maintainer of a 7000 star Github project?

### ISSUE THREAD

**Issue by WonderCsabo** [NativeDevelopmentMeetup/NativeDevelopmentMeetup#13]
I became involved with open source development through the AndroidAnnotations library, shifting from user to power user, bug reporter contributor and finally project maintainer.

In this talk i will give a brief introduction on how to interact with open source projects both as a user and as a developer.

Agenda:
- Version control
- Documentation
- Handling users
- Continuous Integration

Csaba Kozák
Android Developer
Supercharge

**Comment by vasarhelyia** [comment]
:+1:
