### ISSUE TITLE
ReactiveX in general, Rx.NET

### ISSUE THREAD

**Issue by silverforge** [NativeDevelopmentMeetup/NativeDevelopmentMeetup#2]
Reactive Extensions built upon the observer pattern to process data/event sequence asynchronously which popularity is growing nowadays not only for .net devs but for JavaScript, Java, Android, Scala, Python, etc.

We used this library on several projects successfully so I'd like to share my experience and some samples on this talk.

What will be mentioned on this meetup? (Hopefully :)
- Data push model
- Observer pattern at a glance
- Cold/Hot observables
- ObserveOn/SubscribeOn
- Rx samples as we used this lib
- How to process huge amount of data arriving from sensors
- Talk :)

**Comment by vasarhelyia** [comment]
:+1:
