### ISSUE TITLE
Case study: Development of a WebRTC enhanced Android app (Rescue Lens)

### ISSUE THREAD

**Issue by balazsbanyai** [NativeDevelopmentMeetup/NativeDevelopmentMeetup#5]
This talk will wrap up the development of an android app that facilitates WebRTC, OpenCV and other various technologies in order to provide a powerful end-user support tool.

Intro about the app: https://www.logmeinrescue.com/features/lens

**Comment by vasarhelyia** [comment]
:+1:

**Comment by dzsooti** [comment]
:+1:
