### ISSUE TITLE
RxAndroid in practice

### ISSUE THREAD

**Issue by richardradics** [NativeDevelopmentMeetup/NativeDevelopmentMeetup#6]
All the cool kids are doing RxAndroid. We all heard a lot about the theory. But how does it look like in practice? Learning by examples and tips for testing.
Warning! Tons of code snippets!

**Agenda**:
- Basic operators
- Advanced operators
- Handling subscriptions
- Testing observables

**Richard Radics**
Android Developer
**Supercharge**

**Comment by vasarhelyia** [comment]
:+1:

**Comment by gergely-sallai** [comment]
:+1:

**Comment by dzsooti** [comment]
:+1:
