### ISSUE TITLE
React Native 

### ISSUE THREAD

**Issue by Marceeex** [NativeDevelopmentMeetup/NativeDevelopmentMeetup#7]
I would like to talk about facebook's "learn once, write anywhere" framework, React Native, from the perspective of a web developer.

It will cover:
- the core idea of react native
- how to get started
- basics of the framework
- when/why to use it
- what is supported in the current version
- extensibility

**Comment by vasarhelyia** [comment]
:+1:

**Comment by dzsooti** [comment]
:+1:

**Comment by judikdavid** [comment]
:+1:
