### ISSUE TITLE
Into to Bitrise automation stack

### ISSUE THREAD

**Issue by viktorbenei** [NativeDevelopmentMeetup/NativeDevelopmentMeetup#8]
I'd like to talk about how we, at Bitrise, approach the problems and pain points of build automation, and the solutions we developed.

Main points:
- What is Bitrise?
- The importance of getting to your first green build as soon as possible
- `bitrise.yml`: Workflows and Steps
- How our CLI and the Website works together
- Future plans

**Comment by vasarhelyia** [comment]
:+1:
