### ISSUE TITLE
Building highly customizable iOS applications on top of a core codebase

### ISSUE THREAD

**Issue by davidkovaccs** [NativeDevelopmentMeetup/NativeDevelopmentMeetup#9]
Creating well packaged, reusable code is not easy in itself but when it comes to large components of an application - from the UI to integration - this becomes quite a challenge. We have recently built a large, multi-country self-care application that will serve as a good case study. I'll speak about how we've solved different problems along the way to create a core codebase that can be easily tailored for special client needs.

**Agenda:**
- Challenges
- Our solution
- Collaborating on the core
- Testing / CI / QA / Release

**David Kovacs**
CTO
**Supercharge**

**Comment by vasarhelyia** [comment]
:+1:
